import { generateArticleText } from "../ai/provider.js";
import { buildArticlePrompt } from "../ai/prompts/article.js";
import {
  GeneratedArticleSchema,
  type GeneratedArticle,
} from "../ai/schemas/article-schema.js";
import { withRetry } from "../utils/rate-limit.js";
import type { Story } from "../utils/dedup.js";

/**
 * Generate a single article from 1-5 source stories.
 *
 * Returns:
 *   GeneratedArticle — success
 *   "reject"         — AI determined the story is off-topic or already covered
 *   null             — generation or parse failure
 */
export async function generateArticle(
  stories: Story[],
  recentTitles: string[] = [],
): Promise<GeneratedArticle | "reject" | null> {
  const prompt = buildArticlePrompt(stories, recentTitles);

  const { text, modelUsed, paid } = await withRetry(() =>
    generateArticleText(prompt, {
      maxOutputTokens: 3000,
      temperature: 0.55,
    }),
  );

  console.log(
    `[generate] Article generated by ${modelUsed}${paid ? " (PAID)" : " (FREE)"}`,
  );

  // Strip potential markdown code fences around JSON
  const cleaned = text
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```\s*$/, "")
    .trim();

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    console.error(
      "[generate] JSON parse failed. Raw output:\n",
      text.slice(0, 500),
    );
    return null;
  }

  // Handle AI-level reject signal — off-topic or already-covered story
  if (
    typeof parsed === "object" &&
    parsed !== null &&
    (parsed as Record<string, unknown>).reject === true
  ) {
    const reason = (parsed as Record<string, unknown>).reason ?? "unspecified";
    console.log(`[generate] AI rejected story: ${reason}`);
    return "reject";
  }

  const result = GeneratedArticleSchema.safeParse(parsed);
  if (!result.success) {
    console.error(
      "[generate] Schema validation failed:",
      result.error.flatten(),
    );
    return null;
  }

  return result.data;
}
